name: Sync Airflow DAGs

on: workflow_dispatch

jobs:
  sync-dags:
    name: Syn DAGs
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # authenticate with gcloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}

      # set up gcloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # sync dags
      - name: Sync DAGs
        run: |
          gsutil rsync cloud-composer/dags gs://us-central1-cloud-composer--77dd3f5a-bucket/dags
